### ISSUE TITLE
Error loading env config: environment variable not found

### ISSUE THREAD

**Issue by zarevskaya** [krivahtoo/stamon#25]
Hello,

I'm trying to test your application but I got this back:

thread 'main' panicked at crates/server/src/config.rs:45:45:
Error loading env config: environment variable not found
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Have a nice day!

**Comment by krivahtoo** [comment]
Hello @zarevskaya ,

How did you run the application?
You don't need to set the environment variables when you run with `cargo run`.

**Comment by zarevskaya** [comment]
I don't set any .env.
I pull the compose. It's all. 😃

**Comment by krivahtoo** [comment]
Ooh, makes sense.
I haven't update/pushed to docker hub yet since `stamon` isn't usable yet.

**Comment by zarevskaya** [comment]
Thank you very much!

I'll start again.
